name: Derivatives Trader Production Workflow
on:
  push:
    tags:
    - production_*
env:
  RELEASE_TYPE: Production
jobs:
  build_test_and_publish:
    name: Build, Test and Publish to Cloudflare Pages Production
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      actions: write
    outputs:
      RELEASE_VERSION: ${{ steps.extract_version.outputs.RELEASE_VERSION }}
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Setup Node
      uses: "./.github/actions/setup_node"
    - name: Install Dependencies
      uses: "./.github/actions/npm_install_from_cache"
    # - name: Download Remote Config Backup File
    #   uses: ./.github/actions/download_remote_config_backup
    #   with:
    #     REMOTE_CONFIG_URL: ${{ vars.REMOTE_CONFIG_URL }}
    - name: Build
      uses: "./.github/actions/build"
      with:
        NODE_ENV: production
        # DATADOG_APPLICATION_ID: ${{ vars.DATADOG_APPLICATION_ID }}
        # IS_GROWTHBOOK_ENABLED: ${{ vars.IS_GROWTHBOOK_ENABLED }}
        # DATADOG_CLIENT_TOKEN: ${{ vars.DATADOG_CLIENT_TOKEN }}
        # DATADOG_CLIENT_TOKEN_LOGS: ${{ vars.DATADOG_CLIENT_TOKEN_LOGS }}
        # DATADOG_SESSION_REPLAY_SAMPLE_RATE: ${{ vars.DATADOG_SESSION_REPLAY_SAMPLE_RATE }}
        # DATADOG_SESSION_SAMPLE_RATE: ${{ vars.DATADOG_SESSION_SAMPLE_RATE }}
        # DATADOG_SESSION_SAMPLE_RATE_LOGS: ${{ vars.DATADOG_SESSION_SAMPLE_RATE_LOGS }}
        # GD_API_KEY: ${{ secrets.GD_API_KEY }}
        # GD_APP_ID: ${{ secrets.GD_APP_ID }}
        # GD_CLIENT_ID: ${{ secrets.GD_CLIENT_ID }}
        # RUDDERSTACK_KEY: ${{ vars.RUDDERSTACK_KEY }}
        # GROWTHBOOK_CLIENT_KEY: ${{ vars.GROWTHBOOK_CLIENT_KEY }}
        # GROWTHBOOK_DECRYPTION_KEY: ${{ vars.GROWTHBOOK_DECRYPTION_KEY }}
        REF_NAME: ${{ github.ref_name }}
        # REMOTE_CONFIG_URL: ${{ vars.REMOTE_CONFIG_URL }}
        # TRUSTPILOT_API_KEY: ${{ secrets.TRUSTPILOT_API_KEY }}
    # - name: Run tests
    #   run: npm test
    - name: Versioning
      uses: "./.github/actions/versioning"
      with:
        RELEASE_TYPE: ${{ env.RELEASE_TYPE }}
    - name: Extract version
      id: extract_version
      run: echo "RELEASE_VERSION=${version}" >> $GITHUB_OUTPUT
    - name: Publish to Cloudflare Pages Production
      uses: "./.github/actions/publish_to_pages_production"
      with:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    - name: Upload Build Artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: build
        path: packages/core/dist
        retention-days: 1